config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'
  resources :home, only: :index do
  end

  resources :events, only: [:show] do
    member do
      get :add_event_subscriber
    end
  end

  namespace :admin do
    root 'events#index'
    resources :categories, except: [:show]
    resources :events, except: [:show]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	#for the tree structure
	acts_as_nested_set
	
	has_many :events
	validates :name, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :category
	has_and_belongs_to_many :users
	validates :name, :description, :category_id, :event_date, presence: true

	#short description for event
	def short_description
		self.description[0..200] + '...'
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :trackable, :validatable
	validates :firstname, :lastname, presence: true
	has_and_belongs_to_many :events

	# show full name
	def fullname
		"#{firstname} #{lastname}"
	end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
	
	before_filter :find_category, :only => [:destroy, :update, :edit]

	def index
		@categories = Category.order('created_at DESC').page(params[:page]).per(15)
	end

	def new
		@category = Category.new
	end

	def edit
	
	end

	def create
		@category = Category.new category_attributes
		if @category.save
			flash[:notice] = 'Category successfully created'
			redirect_to admin_categories_path
		else
			flash[:notice] = @category.errors.full_messages.join(", ")
			render action: 'new'
		end
	end

	def update
		if @category.update_attributes category_attributes
			flash[:notice] = 'Category successfully created'
			redirect_to admin_categories_path
		else
			flash[:notice] = @category.errors.full_messages.join(", ")
			render action: 'edit'
		end
	end

	def destroy
		if @category.destroy
			flash[:notice] = 'Category successfully removed'
		else
			flash[:notice] = @category.errors.full_messages.join(", ")
		end
		redirect_to admin_categories_path
	end

	private
		def category_attributes
			params.require(:category).permit(:name, :parent_id)
		end

		def find_category
			@category = Category.find(params[:id])
		end

		def model_class
			
		end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController

	before_filter :find_event, :only => [:destroy, :update, :edit]

	def index
		@events = Event.order('event_date ASC').page(params[:page]).per(15)
	end

	def new
		@event = Event.new
	end

	def edit
	
	end

	def create
		@event = Event.new event_attributes
		if @event.save
			flash[:notice] = 'Event successfully created'
			redirect_to admin_events_path
		else
			flash[:notice] = @event.errors.full_messages.join(", ")
			render action: 'new'
		end
	end

	def update
		if @event.update_attributes event_attributes
			flash[:notice] = 'Event successfully created'
			redirect_to admin_events_path
		else
			flash[:notice] = @event.errors.full_messages.join(", ")
			render action: 'edit'
		end
	end

	def destroy
		if @event.destroy
			flash[:notice] = 'Event successfully removed'
		else
			flash[:notice] = @event.errors.full_messages.join(", ")
		end
		redirect_to admin_events_path
	end

	private
		def event_attributes
			params.require(:event).permit(:name, :description, :category_id, :event_date)
		end

		def find_event
			@event = Event.find(params[:id])
		end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_action :authorize_admin

	private
		#access to admin panel
		def authorize_admin
			unless current_user.try(:admin?)
				flash[:notice] = "You do not have access to the administrative panel!"
		  	redirect_to root_path
			end
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
		#add custom parameters
		def configure_permitted_parameters
			devise_parameter_sanitizer.for(:sign_up) << :firstname
			devise_parameter_sanitizer.for(:sign_up) << :lastname
			devise_parameter_sanitizer.for(:account_update) << :firstname
			devise_parameter_sanitizer.for(:account_update) << :lastname
		end

		def user_params
	    params.require(:user).permit(:email, :password)
	  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def show
		@event = Event.find(params[:id])
	end

	#add participant to event
	def add_event_subscriber
		event = Event.find(params[:id])
		user = User.find(params[:user_id])
		if !event.users.exists?(user.id)
			event.users << user
			@del = true
		else
			event.users.delete(user)
			@del = false
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		@events = Event.includes(:users).order('event_date ASC')
		if params[:category_id].present?
			categories_array = Category.find(params[:category_id]).self_and_descendants.map {|c| c.id}
			@events = @events.where('category_id in (?)', categories_array)
		end
		if params[:user_id].present? && params[:user_id].to_i > 0
			@events = @events.where(users: {id: params[:user_id].to_i})
		end
		@events = @events.page(params[:page]).per(15)
		respond_to do |format|
			format.html
			format.js
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	private
		def user_params
	    params.require(:user).permit(:email, :password)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#check namespace
	def namespace_admin?
		controller.class.name.split("::").first=="Admin"
	end

	#classification controller in admin panel
	def classification_controller(name)
		controller_name.classify == name ? 'active' : ''
	end

	#list of participants event with a limited number
	def event_subscribers_with_name(event, limit=nil)
		subscriber_str = ''
		unless limit.nil?
			subscribers = event.users.limit(limit)
		else
			subscribers = event.users
		end
		subscribers.each do |subscriber|
			subscriber_str += subscriber.fullname + ', '
		end	
		subscriber_str[0..subscriber_str.length - 3]
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/edit.html.haml
.col-xs-4
	%h2 Edit category
	= form_for @category, :url => admin_category_path, method: :patch, :html => { :multipart => true } do |f|
		.form-group
			= f.label :name
			%br/
			= f.text_field :name, class: "form-control"
		.form-group
			= f.label :parent
			%br/
			= f.select :parent_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.name}" }, { include_blank: true }, class: "form-control"

		%div= f.submit "Edit", class: 'btn btn-primary'

app/views/admin/categories/index.html.haml
.col-xs-9
	.add_new_event
		= link_to 'Add category', new_admin_category_path, class: 'btn btn-primary'
	.events_block
		- if @categories.any?
			.categories_list
				%table.table.table-hover
					%colgroup
						%col{style: "width: 25%;"}
						%col{style: "width: 25%;"}
						%col{style: "width: 15%;"}
					%thead
						%tr
							%th
								= 'Name'
							%th
								= 'Parent'
					%tbody
						- @categories.each do |category|
							%tr{ id: "category_#{category.id}"}
								%td.align-center
									= category.name
								%td.align-center
									- if category.parent_id
										= Category.find(category.parent_id).name
									- else
										= '-'
								%td.actions
									= link_to 'Edit', edit_admin_category_path(category.id), :class => 'edit'
									&nbsp;
									= link_to 'Delete', admin_category_path(category.id), class: 'delete', data: { confirm: "Are you sure?" }, method: :delete
			.pagination_block
				= paginate @categories, :window => 2
		- else
			Categories not found
.col-xs-3
	= render :partial => 'shared/admin_right_menu'

app/views/admin/categories/new.html.haml
.col-xs-4
	%h2 New category
	= form_for @category, :url => admin_categories_path, method: :post, :html => { :multipart => true } do |f|
		.form-group
			= f.label :name
			%br/
			= f.text_field :name, class: "form-control"
		.form-group
			= f.label :parent
			%br/
			= f.select :parent_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.name}" }, { include_blank: true }, class: "form-control"

		%div= f.submit "Save", class: 'btn btn-primary'

app/views/admin/events/edit.html.haml
.col-xs-4
	%h2 Edit event
	= form_for @event, :url => admin_event_path, method: :patch, :html => { :multipart => true } do |f|
		.form-group
			= f.label :name
			%br/
			= f.text_field :name, class: "form-control"
		.form-group
			= f.label :description
			%br/
			= f.text_area :description, class: "form-control"
		.form-group
			= f.label :category
			%br/
			= f.select :category_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.name}" }, class: "form-control"
		.form-group
			= f.label :event_date
			%br/
			= f.text_field :event_date, :value => @event.event_date.strftime('%d/%m/%Y %H:%M'), class: "form-control", :id => 'event_datepicker'
		%div= f.submit "Update", class: 'btn btn-primary'

app/views/admin/events/index.html.haml
.col-xs-9
	.add_new_event
		= link_to 'Add event', new_admin_event_path, class: 'btn btn-primary'
	.events_block
		- if @events.any?
			.events_list
				%table.table.table-hover
					%colgroup
						%col{style: "width: 25%;"}
						%col{style: "width: 35%;"}
						%col{style: "width: 15%;"}
						%col{style: "width: 15%;"}
						%col{style: "width: 10%;"}
					%thead
						%tr
							%th
								= 'Name'
							%th
								= 'Short description'
							%th
								= 'Category'
							%th
								= 'Event date'
					%tbody
						= render :partial => 'admin/shared/events_list', locals: {events: @events}
			.pagination_block
				= paginate @events, :window => 2
		- else
			Events not found
.col-xs-3
	= render :partial => 'shared/admin_right_menu'

app/views/admin/events/new.html.haml
.col-xs-4
	%h2 New event
	= form_for @event, :url => admin_events_path, method: :post, :html => { :multipart => true } do |f|
		.form-group
			= f.label :name
			%br/
			= f.text_field :name, class: "form-control"
		.form-group
			= f.label :description
			%br/
			= f.text_area :description, class: "form-control"
		.form-group
			= f.label :category
			%br/
			= f.select :category_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.name}" }, class: "form-control"
		.form-group
			= f.label :event_date
			%br/
			= f.text_field :event_date, class: "form-control", :id => 'event_datepicker'
		%div= f.submit "Save", class: 'btn btn-primary'

app/views/admin/shared/_events_list.html.haml
- events.each do |event|
	%tr{ id: "event_#{event.id}"}
		%td.align-center
			= event.name
		%td.align-center
			= event.short_description
		%td.align-center
			= event.category.name
		%td.align-center
			= event.event_date.strftime("%d/%m/%Y")
		%td.actions
			= link_to 'Edit', edit_admin_event_path(event.id), :class => 'edit'
			&nbsp;
			= link_to 'Delete', admin_event_path(event.id), class: 'delete', data: { confirm: "Are you sure?" }, method: :delete

app/views/events/add_event_subscriber.js.erb
<% if @del %>
	$('.add_subscribe_link').text('unsubscribe from event');
<% else %>
	$('.add_subscribe_link').text('sign up for event');
<% end %>

app/views/events/show.html.haml
.event_block
	.event_name
		= @event.name
	.event_body
		= @event.description
	.event_information
		.event_participants
			= "Participants: " + event_subscribers_with_name(@event)
		.event_date_inf
			= @event.event_date.strftime('%d/%m/%Y %H:%M')
- if current_user
	= link_to @event.users.exists?(current_user.id) ? 'unsubscribe from event' : 'sign up for event', add_event_subscriber_event_path(@event.id, user_id: current_user.id), class: 'btn btn-primary add_subscribe_link', remote: true

app/views/home/index.html.haml
.col-xs-3
	= render :partial => 'shared/events_filter'
.col-xs-9
	%ul.list-group
		.events_list
			= render :partial => 'shared/events_list', locals: {events: @events}
	.pagination_block
		= paginate @events, :window => 2, :remote => true, params: { appended: true, category_id: params[:category_id], user_id: params[:user_id] }

app/views/home/index.js.erb
<% if params[:appended] %>
	$('.events_list').append("<%= escape_javascript(render(partial: "shared/events_list", locals: {events: @events})) %>")
<% else %>
	$('.events_list').html("<%= escape_javascript(render(partial: "shared/events_list", locals: {events: @events})) %>")
<% end %>
$('.pagination_block').html("<%= escape_javascript(paginate(@events , window: 2, :remote => true, params: { appended: true, category_id: params[:category_id], user_id: params[:user_id] })) %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
	<title>Newsline</title>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>
</head>
<body>
	<% if namespace_admin? %>
		<%= render :partial => 'shared/admin_navbar' %>
	<% else %>
		<%= render :partial => 'shared/navbar' %>
	<% end %>
	<div class="container-fluid">
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
		<%= yield %>
	</div>
</body>
</html>

app/views/shared/_admin_navbar.html.haml
%nav.navbar.navbar-default
	.container-fluid
		/ Brand and toggle get grouped for better mobile display
		.navbar-header
			%a.navbar-brand{:href => admin_root_path} Administration panel
		/ Collect the nav links, forms, and other content for toggling
		#bs-example-navbar-collapse-1.collapse.navbar-collapse
			%ul.nav.navbar-nav.navbar-right
				- if user_signed_in?
					%li
						%span
							= "Hello, #{current_user.fullname}"
					%li	
						= link_to 'Home', root_path
					%li	
						= link_to 'Edit', edit_user_registration_path(current_user)
					%li	
						= link_to 'Logout', destroy_user_session_path, :method => :delete

app/views/shared/_admin_right_menu.html.haml
%ul.nav.nav-pills.nav-stacked
	%li{class: classification_controller('Event')}
		= link_to 'Events', admin_events_path
	%li{class: classification_controller('Category')}
		= link_to 'Categories', admin_categories_path

app/views/shared/_events_filter.html.haml
%h2
	= 'Categories'
.categories_filter_block
	- nested_set_options(Category){|i| [i.level,i.name] }.each do |cat|
		= link_to root_path(category_id: cat[1]), { remote: true, class: params[:category_id].to_i == cat[1].to_i ? 'active' : '', style: "padding-left: #{cat[0][0] * 20}px;", :data => {id: cat[1]} } do
			%i{class: "fa #{params[:category_id].to_i == cat[1].to_i ? 'fa-check-circle' : 'fa-check-circle-o'}"}
			= cat[0][1]
		%br
= form_tag '', :method => :get, remote: true, class: 'filters_form' do
	= hidden_field_tag :category_id
	%h2
		= 'Participant'
	.participants_filter_block
		= select_tag :user_id, options_from_collection_for_select(User.order('firstname, lastname'), :id, :fullname), {:prompt => "Select participant", class: "form-control", :onClick => "$(this.form).find('button').click();"}
	= button_tag "filter", {style: 'display: none;'}

app/views/shared/_events_list.html.haml
- if events.length > 0
	- events.each do |event|
		%li.list-group-item.event_block
			.event_name
				= link_to event.name, event_path(event)
			.event_body
				= event.short_description
			.event_information
				.event_participants
					= event_subscribers_with_name(event, 10)
				.event_date_inf
					= event.event_date.strftime('%d/%m/%Y %H:%M')
- else
	Results not found

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default
	.container-fluid
		/ Brand and toggle get grouped for better mobile display
		.navbar-header
			%a.navbar-brand{:href => root_path} NewsLine
		/ Collect the nav links, forms, and other content for toggling
		#bs-example-navbar-collapse-1.collapse.navbar-collapse
			%ul.nav.navbar-nav.navbar-right
				- if user_signed_in?
					%li
						%span
							= "Hello, #{current_user.fullname}"
					- if current_user.try(:admin?)
						%li	
							= link_to 'Admin', admin_root_path
					%li	
						= link_to 'Edit', edit_user_registration_path(current_user)
					%li	
						= link_to 'Logout', destroy_user_session_path, :method => :delete
				- else
					%li
						= link_to 'Sign in', new_user_session_path
					%li
						= link_to 'Registration', new_user_registration_path